DATA :
  NAME : TextOCR
  IMAGE_SIZE : 640
  VALID_IMAGE_SIZE : 1280
  DATA_DIR : TextOCR/
  TRAIN_IMG_DIR : TextOCR/train
  TRAIN_LABEL : TextOCR/TextOCR_train.json
  VALID_IMG_DIR : TextOCR/train
  VALID_LABEL : TextOCR/TextOCR_val.json
 
  MAX_LEN : 8
  SAMPLE_TEXT : 2

MODEL : 
    PARAMS : 
        WEIGHT_DECAY : 1e-6
        BATCH_SIZE : 4
        MAX_STEPS : 400000
    BACKBONE : 
      NAME : vovnet
      PRETRAINED : backbone/vovnet39.pth
    OPTIMIZER : Adam
    SCHEDULER : CustomCosineAnnealingWarmupRestarts
    SCHEDULER_PARAMS :
      max_lr: 3e-4
      min_lr: 5e-5